POST https://generativelanguage.googleapis.com
    /v1beta
    /models
    /gemini-1.5-flash:generateContent
    ?key=AIzaSyBLI0bfwny7l-Hx56hI93CxYpHQZXxxnyQ
Content-Type: application/json

{
  "contents": [
    {
      "parts": [
        {
          "text": "오늘 점심 메뉴 추천해줘. 30자 이내로 대답해줘"
        }
      ]
    }
  ]
}

###